Prevent segfault when attempting to set readonly property
gagern/node-libtidy pull request #16
Opened 2017-04-10 16:11 UTC by jokester

The following code caused segfault in osx / linux. I suppose a JS exception would be more friendly.

```js
var libtidy = require('libtidy');
var c = new libtidy.TidyDoc();
c.optSet(8); // 8 for the only readonly option "doctype-mode"
```

Also changed a few tests to call `to.throw()`: the `throw` assertion does not work without `()`).

2017-04-10 22:02 UTC, gagern requested changes
Thanks a lot for bringing this up and fixing it. And for fixing the throws unit tests in the process. Some minor changes and I can merge this in.

2017-04-10 22:02 UTC, gagern commented on test/opt-test.js
> +      var opt = doc.getOption(8);
Better refer to the option by name, for reasons [explained in the API doc](https://github.com/gagern/node-libtidy/blob/master/API.md#tidyoptionid).

2017-04-10 22:02 UTC, gagern commented on test/opt-test.js
> +    it("setting a readonly option throw", function() {
Grammar: “throws”.

2017-04-10 22:02 UTC, gagern commented on test/opt-test.js
> +      expect(function() { doc.optSet(8); }).to.throw(Error, /' is readonly/);
Use the name here, too.

2017-04-11 00:28 UTC, jokester commented on test/opt-test.js
> +    it("setting a readonly option throw", function() {
fixed

2017-04-11 00:29 UTC, jokester commented on test/opt-test.js
> +      expect(function() { doc.optSet(8); }).to.throw(Error, /' is readonly/);
Fixed the names

2017-04-13 23:47 UTC, gagern approved these changes

2017-04-13 23:47 UTC, merged